### ISSUE TITLE
Add `n_init` to Leiden

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic-native#17]
Cross-post from https://github.com/microsoft/graspologic/issues/757

Would like to have a way to set the number of initializations of Leiden, and return the best modularity final partition. 

Discussed in the thread above, as it is costly to convert to-from python, we thought it would make sense to do this in Rust. 

cc: @dwaynepryce @loftusa

**Comment by loftusa** [comment]
totally down to take a crack at this, although I likely won't have the bandwidth for a couple weeks.

**Comment by bdpedigo** [comment]
Related, but I should possibly open another issue - it's also important to be able to control this process by setting a random state/seed to get reproducible results, but I have no idea how this works in Rust.

**Comment by dwaynepryce** [comment]
There's already a seed going into it, so we don't have to worry about that part.

@loftusa I can probably get to it sooner than that, but I'll add you to the PR if you want to learn-by-review?

**Comment by bdpedigo** [comment]
> There's already a seed going into it, so we don't have to worry about that part.

is the seed just not exposed to the python implementation then?

**Comment by dwaynepryce** [comment]
It is exposed - are you not seeing it?

Maybe the wrapper isn't exposing it;

https://github.com/microsoft/graspologic-native/blob/dev/packages/pyo3/src/lib.rs#L114

**Comment by dwaynepryce** [comment]
https://github.com/microsoft/graspologic/blob/dev/graspologic/partition/leiden.py#L207

**Comment by bdpedigo** [comment]
oops, you're right, I made a silly

**Comment by loftusa** [comment]
> There's already a seed going into it, so we don't have to worry about that part.
> 
> @loftusa I can probably get to it sooner than that, but I'll add you to the PR if you want to learn-by-review?

Sure

**Comment by dwaynepryce** [comment]
This should be done, I'll expose it in graspologic after this finishes publishing

**Comment by bdpedigo** [comment]
amazing, thank you!
